### ISSUE TITLE
Cannot quit mpv due to hanging process

### ISSUE THREAD

**Issue by GribanovIvan** [tnychn/mpv-discord#1] opened 2021-01-22 17:01 UTC
when i trying watch any m3u8 video AV can stops. but remaining time continues to countdown, sometimes ignore pause.

my system: ArchLinux x86_64
mpv from: official archlinux repo
hardware: HP255-G7
how i launch mpv: mpv https://de8.libria.fun/videos/ts/8339/0001-hd/playlist.m3u8 https://de8.libria.fun/videos/ts/8339/0002-hd/playlist.m3u8 https://de8.libria.fun/videos/ts/8339/0003-hd/playlist.m3u8 https://de8.libria.fun/videos/ts/8339/0004-hd/playlist.m3u8 https://de8.libria.fun/videos/ts/8339/0005-hd/playlist.m3u8 https://de8.libria.fun/videos/ts/8339/0006-hd/playlist.m3u8 https://de8.libria.fun/videos/ts/8339/0007-hd/playlist.m3u8 https://de8.libria.fun/videos/ts/8339/0008-hd/playlist.m3u8 https://de8.libria.fun/videos/ts/8339/0009-hd/playlist.m3u8 https://de8.libria.fun/videos/ts/8339/0010-hd/playlist.m3u8 https://de8.libria.fun/videos/ts/8339/0011-hd/playlist.m3u8 https://de8.libria.fun/videos/ts/8339/0012-hd/playlist.m3u8  --force-media-title='Непоседливая лисица Сэнко / Sewayaki Kitsune no Senko-san'

maybe problems with resuming playbacks.. not sure

also i can't close mpv without killing process

**Comment by tnychn** [comment] 2021-01-23 08:48
It seems that the root cause is there is that one of the functions is blocking the loop, which makes the process hangs. That's why the remaining time countdown does not stop and pauses are not handled.

**Comment by tnychn** [comment] 2021-01-24 06:09
Please let me know if the issue persists. I'll close this issue for now.

**Closed by tnychn** 2021-01-24 06:09 UTC
Labels: bug

**Comment by indeedwatson** [comment] 2021-01-31 16:56
Hey, just started using this and the issue is still happening.

**Comment by tnychn** [comment] 2021-02-01 11:18
Could you please provide more information for me to debug?
* what OS you are using
* your mpv and mpv-discord versions
* the command line arguments you used to start mpv

**Comment by indeedwatson** [comment] 2021-02-01 14:05
arch linux, latest version of mpv-discord and mpv 0.33, no special cli arguments, just mpv. The process hangs and consumes 90% cpu, so obviously I'm gonna stop using it, but i just wanted to report the issue.

**Comment by tnychn** [comment] 2021-02-04 19:43
Thanks for your report and sorry for the late response!
But I'm not able to reproduce the issue after it was (supposedly) fixed at e2c90b6.

Maybe a possible workaround is to kill the process by calling `os.execute` in the Lua script.
This is confusing...🤔 guess I'll have to do some more investigation on this issue.

**Comment by GribanovIvan** [comment] 2021-02-15 19:21
quit bug seems fixed, but timer bug no...

https://user-images.githubusercontent.com/40523124/107985957-ca6f3380-6fd3-11eb-9e2a-53ddc9b6d67d.mp4
